//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.1.2-build.19+gd2624816c7
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 2.8 -InputFile Success.json
//       
//       Input file:
//           Success.json (20793 bytes created 18:49+02:00 Sep 7 2022)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   248 |
// |--------------------------+-------|
// | Expression animators     |    34 |
// | KeyFrame animators       |    34 |
// | Reference parameters     |    34 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     3 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     2 |
// | ShapeVisuals             |     2 |
// |--------------------------+-------|
// | ContainerShapes          |    11 |
// | CompositionSpriteShapes  |    18 |
// |--------------------------+-------|
// | Brushes                  |     9 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedVisuals
{
    // Name:        Anim8*
    // Frame rate:  25 fps
    // Frame count: 55
    // Duration:    2200.0 mS
    sealed class Success
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 2.200 seconds.
        internal const long c_durationTicks = 22000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            if (Success_AnimatedVisual.IsRuntimeCompatible())
            {
                var res = 
                    new Success_AnimatedVisual(
                        compositor
                        );
                    res.CreateAnimations();
                    return res;
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 55d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 25d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(22000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 55d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Success_AnimatedVisual : Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 22000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0;
            CompositionColorBrush _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1;
            CompositionColorBrush _animatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8;
            CompositionColorBrush _colorBrush_AlmostDarkCyan_FF0065BD;
            CompositionColorBrush _colorBrush_AlmostDodgerBlue_FF0C81E8;
            CompositionColorBrush _colorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB;
            CompositionColorBrush _colorBrush_SemiTransparentWhite;
            CompositionContainerShape _containerShape_00;
            CompositionContainerShape _containerShape_01;
            CompositionContainerShape _containerShape_02;
            CompositionContainerShape _containerShape_03;
            CompositionContainerShape _containerShape_04;
            CompositionContainerShape _containerShape_05;
            CompositionContainerShape _containerShape_06;
            CompositionContainerShape _containerShape_07;
            CompositionContainerShape _containerShape_08;
            CompositionContainerShape _containerShape_09;
            CompositionContainerShape _containerShape_10;
            CompositionEllipseGeometry _ellipse_9p678;
            CompositionEllipseGeometry _ellipse_177p719;
            CompositionPath _path;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_3;
            CompositionPathGeometry _pathGeometry_4;
            CompositionPathGeometry _pathGeometry_5;
            CompositionSpriteShape _spriteShape_01;
            CompositionSpriteShape _spriteShape_02;
            CompositionSpriteShape _spriteShape_03;
            CompositionSpriteShape _spriteShape_17;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            CubicBezierEasingFunction _cubicBezierEasingFunction_3;
            CubicBezierEasingFunction _cubicBezierEasingFunction_4;
            ExpressionAnimation _rootProgress;
            ScalarKeyFrameAnimation _scalarAnimation_0_to_1_0;
            ScalarKeyFrameAnimation _scalarAnimation_0_to_1_1;
            ScalarKeyFrameAnimation _scalarAnimation_0p3_to_0p916;
            ScalarKeyFrameAnimation _scalarAnimation_0p3_to_1p011;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_4;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_7;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            ColorKeyFrameAnimation CreateColorKeyFrameAnimation(float initialProgress, Color initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InterpolationColorSpace = CompositionColorSpace.Rgb;
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-1401.5F, -1457.5F));
                    builder.AddLine(new Vector2(-1027.48999F, -1672.49902F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - PreComp layer: BG
            // - - - Layer aggregator
            // - - Layer: stroke4
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-1401.5F, -1457.5F));
                    builder.AddLine(new Vector2(-1372.35095F, -1474.47705F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - PreComp layer: BG
            // - - - Layer aggregator
            // - - Layer: stroke3
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-1401.5F, -1457.5F));
                    builder.AddLine(new Vector2(-1117.45398F, -1623.49304F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-894.5F, -1726F));
                    builder.AddLine(new Vector2(-869.5F, -1726F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - Layer: Shape Layer 3
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-72F, 6F));
                    builder.AddLine(new Vector2(-28F, 49F));
                    builder.AddLine(new Vector2(75F, -54F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x02, 0x00, 0x65, 0xBD), StepThenHoldEasingFunction());
                // Frame 16.
                // SemiTransparentAlmostDarkCyan_020065BD
                result.InsertKeyFrame(0.290909082F, Color.FromArgb(0x02, 0x00, 0x65, 0xBD), HoldThenStepEasingFunction());
                // Frame 26.
                // AlmostDarkCyan_FF0065BD
                result.InsertKeyFrame(0.472727269F, Color.FromArgb(0xFF, 0x00, 0x65, 0xBD), CubicBezierEasingFunction_2());
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x02, 0x00, 0x65, 0xBD), StepThenHoldEasingFunction());
                // Frame 18.
                // SemiTransparentAlmostDarkCyan_020065BD
                result.InsertKeyFrame(0.327272713F, Color.FromArgb(0x02, 0x00, 0x65, 0xBD), HoldThenStepEasingFunction());
                // Frame 28.
                // AlmostDarkCyan_FF0065BD
                result.InsertKeyFrame(0.5090909F, Color.FromArgb(0xFF, 0x00, 0x65, 0xBD), CubicBezierEasingFunction_2());
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x02, 0x0C, 0x81, 0xE8), StepThenHoldEasingFunction());
                // Frame 15.
                // SemiTransparentAlmostDodgerBlue_020C81E8
                result.InsertKeyFrame(0.272727281F, Color.FromArgb(0x02, 0x0C, 0x81, 0xE8), HoldThenStepEasingFunction());
                // Frame 25.
                // AlmostDodgerBlue_FF0C81E8
                result.InsertKeyFrame(0.454545468F, Color.FromArgb(0xFF, 0x0C, 0x81, 0xE8), CubicBezierEasingFunction_2());
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0()
            {
                if (_animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0 != null) { return _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0; }
                var result = _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0 = _c.CreateColorBrush();
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1()
            {
                if (_animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1 != null) { return _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1; }
                var result = _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1 = _c.CreateColorBrush();
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8()
            {
                if (_animatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8 != null) { return _animatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8; }
                var result = _animatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8 = _c.CreateColorBrush();
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostDarkCyan_FF0065BD()
            {
                return (_colorBrush_AlmostDarkCyan_FF0065BD == null)
                    ? _colorBrush_AlmostDarkCyan_FF0065BD = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x65, 0xBD))
                    : _colorBrush_AlmostDarkCyan_FF0065BD;
            }

            CompositionColorBrush ColorBrush_AlmostDodgerBlue_FF0C81E8()
            {
                return (_colorBrush_AlmostDodgerBlue_FF0C81E8 == null)
                    ? _colorBrush_AlmostDodgerBlue_FF0C81E8 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x0C, 0x81, 0xE8))
                    : _colorBrush_AlmostDodgerBlue_FF0C81E8;
            }

            // - - - Layer aggregator
            // - - Layer: Shape Layer 1
            // ShapeGroup: Ellipse 1 Offset:<9.719, 2.719>
            CompositionColorBrush ColorBrush_AlmostDodgerBlue_FF118EFC()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x11, 0x8E, 0xFC));
            }

            CompositionColorBrush ColorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB()
            {
                return (_colorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB == null)
                    ? _colorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB = _c.CreateColorBrush(Color.FromArgb(0x7F, 0x97, 0xCC, 0xFB))
                    : _colorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB;
            }

            CompositionColorBrush ColorBrush_SemiTransparentWhite()
            {
                return (_colorBrush_SemiTransparentWhite == null)
                    ? _colorBrush_SemiTransparentWhite = _c.CreateColorBrush(Color.FromArgb(0x7F, 0xFF, 0xFF, 0xFF))
                    : _colorBrush_SemiTransparentWhite;
            }

            // - Layer aggregator
            // Layer: Shape Layer 3
            CompositionColorBrush ColorBrush_White()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF));
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Layer: Bolas1
            CompositionContainerShape ContainerShape_00()
            {
                if (_containerShape_00 != null) { return _containerShape_00; }
                var result = _containerShape_00 = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_01());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: Bolas1
            CompositionContainerShape ContainerShape_01()
            {
                if (_containerShape_01 != null) { return _containerShape_01; }
                var result = _containerShape_01 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-1108F, -1440F);
                result.Offset = new Vector2(1729.5F, 1918.5F);
                var shapes = result.Shapes;
                // ShapeGroup: Ellipse 3 Scale:0.85671,0.85671, Offset:<-819.535, -1371.645>
                shapes.Add(SpriteShape_04());
                // ShapeGroup: Ellipse 1 Scale:1.4088,1.4088, Offset:<-1282.949, -1147.881>
                shapes.Add(SpriteShape_05());
                // ShapeGroup: Ellipse 2 Scale:1.4088,1.4088, Offset:<-1151.238, -1723.625>
                shapes.Add(SpriteShape_06());
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Layer: Bolas2
            CompositionContainerShape ContainerShape_02()
            {
                if (_containerShape_02 != null) { return _containerShape_02; }
                var result = _containerShape_02 = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_03());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: Bolas2
            CompositionContainerShape ContainerShape_03()
            {
                if (_containerShape_03 != null) { return _containerShape_03; }
                var result = _containerShape_03 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-1112F, -1428F);
                result.Offset = new Vector2(1729.5F, 1918.5F);
                var shapes = result.Shapes;
                // ShapeGroup: Ellipse 2 Scale:0.64361,0.64361, Offset:<-1435.793, -1556.371>
                shapes.Add(SpriteShape_07());
                // ShapeGroup: Ellipse 3 Scale:0.64361,0.64361, Offset:<-952.029, -1150.197>
                shapes.Add(SpriteShape_08());
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Layer: cruz1
            CompositionContainerShape ContainerShape_04()
            {
                if (_containerShape_04 != null) { return _containerShape_04; }
                var result = _containerShape_04 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-882.375F, -1726F);
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Shape 1 RotationDegrees:-90
                shapes.Add(SpriteShape_09());
                // ShapeGroup: Shape 2
                shapes.Add(SpriteShape_10());
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Layer: cruz2
            CompositionContainerShape ContainerShape_05()
            {
                if (_containerShape_05 != null) { return _containerShape_05; }
                var result = _containerShape_05 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-882.375F, -1726F);
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Shape 1 RotationDegrees:-90
                shapes.Add(SpriteShape_11());
                // ShapeGroup: Shape 2
                shapes.Add(SpriteShape_12());
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Layer: cruz3
            CompositionContainerShape ContainerShape_06()
            {
                if (_containerShape_06 != null) { return _containerShape_06; }
                var result = _containerShape_06 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-882.375F, -1726F);
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Shape 1 RotationDegrees:-90
                shapes.Add(SpriteShape_13());
                // ShapeGroup: Shape 2
                shapes.Add(SpriteShape_14());
                return result;
            }

            // Layer aggregator
            // Layer: Shape Layer 1
            CompositionContainerShape ContainerShape_07()
            {
                if (_containerShape_07 != null) { return _containerShape_07; }
                var result = _containerShape_07 = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_08());
                return result;
            }

            // - Layer aggregator
            // Layer: Shape Layer 1
            CompositionContainerShape ContainerShape_08()
            {
                if (_containerShape_08 != null) { return _containerShape_08; }
                var result = _containerShape_08 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(9.71899986F, 2.7190001F);
                result.Offset = new Vector2(388.391998F, 354.312012F);
                // ShapeGroup: Ellipse 1 Offset:<9.719, 2.719>
                result.Shapes.Add(SpriteShape_15());
                return result;
            }

            // Layer aggregator
            // Layer: Shape Layer 2
            CompositionContainerShape ContainerShape_09()
            {
                if (_containerShape_09 != null) { return _containerShape_09; }
                var result = _containerShape_09 = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_10());
                return result;
            }

            // - Layer aggregator
            // Layer: Shape Layer 2
            CompositionContainerShape ContainerShape_10()
            {
                if (_containerShape_10 != null) { return _containerShape_10; }
                var result = _containerShape_10 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(9.71899986F, 2.7190001F);
                result.Offset = new Vector2(388.281006F, 354.312012F);
                // ShapeGroup: Ellipse 1 Offset:<9.719, 2.719>
                result.Shapes.Add(SpriteShape_16());
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_9p678()
            {
                if (_ellipse_9p678 != null) { return _ellipse_9p678; }
                var result = _ellipse_9p678 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(9.67749977F, 9.67749977F);
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_177p719()
            {
                if (_ellipse_177p719 != null) { return _ellipse_177p719; }
                var result = _ellipse_177p719 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(177.718994F, 177.718994F);
                return result;
            }

            CompositionPath Path()
            {
                if (_path != null) { return _path; }
                var result = _path = new CompositionPath(Geometry_0());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Offset:<1729.5, 1918.5>
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry(Path());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: stroke2
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry(Path());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: stroke4
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: stroke3
            CompositionPathGeometry PathGeometry_3()
            {
                if (_pathGeometry_3 != null) { return _pathGeometry_3; }
                var result = _pathGeometry_3 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            CompositionPathGeometry PathGeometry_4()
            {
                return (_pathGeometry_4 == null)
                    ? _pathGeometry_4 = _c.CreatePathGeometry(new CompositionPath(Geometry_3()))
                    : _pathGeometry_4;
            }

            // - Layer aggregator
            // Layer: Shape Layer 3
            CompositionPathGeometry PathGeometry_5()
            {
                if (_pathGeometry_5 != null) { return _pathGeometry_5; }
                var result = _pathGeometry_5 = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<1729.5, 1918.5>, Scale:<1.0004, 0.99990004>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.00039995F, 0F, 0F, 0.999899983F, 1729.5F, 1918.5F), ColorBrush_SemiTransparentWhite());;
                result.StrokeBrush = ColorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 92F;
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<1818.5, 2059.5>, Scale:<1.0004, 0.99990004>
                var geometry = PathGeometry_1();
                if (_spriteShape_01 != null) { return _spriteShape_01; }
                var result = _spriteShape_01 = CreateSpriteShape(geometry, new Matrix3x2(1.00039995F, 0F, 0F, 0.999899983F, 1818.5F, 2059.5F), ColorBrush_SemiTransparentWhite());;
                result.Scale = new Vector2(0F, 0F);
                result.StrokeBrush = ColorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 92F;
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<2288.5, 1790.5>, Scale:<1.0004, 0.99990004>
                var geometry = PathGeometry_2();
                if (_spriteShape_02 != null) { return _spriteShape_02; }
                var result = _spriteShape_02 = CreateSpriteShape(geometry, new Matrix3x2(1.00039995F, 0F, 0F, 0.999899983F, 2288.5F, 1790.5F), ColorBrush_SemiTransparentWhite());;
                result.Scale = new Vector2(0F, 0F);
                result.StrokeBrush = ColorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 92F;
                return result;
            }

            // - PreComp layer: BG
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                // Offset:<1950.5, 2175.5>, Scale:<1.0004, 0.99990004>
                var geometry = PathGeometry_3();
                if (_spriteShape_03 != null) { return _spriteShape_03; }
                var result = _spriteShape_03 = CreateSpriteShape(geometry, new Matrix3x2(1.00039995F, 0F, 0F, 0.999899983F, 1950.5F, 2175.5F), ColorBrush_SemiTransparentWhite());;
                result.Scale = new Vector2(0F, 0F);
                result.StrokeBrush = ColorBrush_SemiTransparentAlmostLightSkyBlue_7F97CCFB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 92F;
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: Bolas1
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                // Offset:<-819.535, -1371.645>, Scale:<0.85671, 0.85671>
                var result = CreateSpriteShape(Ellipse_9p678(), new Matrix3x2(0.856710017F, 0F, 0F, 0.856710017F, -819.534973F, -1371.64502F));;
                result.StrokeBrush = ColorBrush_AlmostDodgerBlue_FF0C81E8();
                result.StrokeThickness = 5F;
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: Bolas1
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                // Offset:<-1282.949, -1147.881>, Rotation:-0.007232962432122753 degrees,
                // Scale:<1.4088, 1.4088>
                var result = CreateSpriteShape(Ellipse_9p678(), new Matrix3x2(1.40880001F, 0F, 0F, 1.40880001F, -1282.94897F, -1147.88098F));;
                result.StrokeBrush = ColorBrush_AlmostDarkCyan_FF0065BD();
                result.StrokeThickness = 5F;
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: Bolas1
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                // Offset:<-1151.238, -1723.625>, Rotation:-0.007232962432122753 degrees,
                // Scale:<1.4088, 1.4088>
                var result = CreateSpriteShape(Ellipse_9p678(), new Matrix3x2(1.40880001F, 0F, 0F, 1.40880001F, -1151.23804F, -1723.625F));;
                result.StrokeBrush = ColorBrush_AlmostDarkCyan_FF0065BD();
                result.StrokeThickness = 5F;
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: Bolas2
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                // Offset:<-1435.793, -1556.371>, Rotation:-0.002296970854695015 degrees,
                // Scale:<0.64361, 0.64361>
                var result = CreateSpriteShape(Ellipse_9p678(), new Matrix3x2(0.643610001F, 0F, 0F, 0.643610001F, -1435.79297F, -1556.37097F));;
                result.StrokeBrush = ColorBrush_AlmostDodgerBlue_FF0C81E8();
                result.StrokeThickness = 8F;
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: Bolas2
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<-952.029, -1150.197>, Rotation:-0.002296970854695015 degrees,
                // Scale:<0.64361, 0.64361>
                var result = CreateSpriteShape(Ellipse_9p678(), new Matrix3x2(0.643610001F, 0F, 0F, 0.643610001F, -952.028992F, -1150.19702F));;
                result.StrokeBrush = ColorBrush_AlmostDodgerBlue_FF0C81E8();
                result.StrokeThickness = 8F;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz1
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<843.572, -2608.05>, Rotation:-90 degrees
                var result = CreateSpriteShape(PathGeometry_4(), new Matrix3x2(0F, -1F, 1F, 0F, 843.572021F, -2608.05005F));;
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz1
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz2
            // Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                // Offset:<843.572, -2608.05>, Rotation:-90 degrees
                var result = CreateSpriteShape(PathGeometry_4(), new Matrix3x2(0F, -1F, 1F, 0F, 843.572021F, -2608.05005F));;
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz2
            // Path 1
            CompositionSpriteShape SpriteShape_12()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz3
            // Path 1
            CompositionSpriteShape SpriteShape_13()
            {
                // Offset:<843.572, -2608.05>, Rotation:-90 degrees
                var result = CreateSpriteShape(PathGeometry_4(), new Matrix3x2(0F, -1F, 1F, 0F, 843.572021F, -2608.05005F));;
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz3
            // Path 1
            CompositionSpriteShape SpriteShape_14()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Shape Layer 1
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_15()
            {
                // Offset:<9.719, 2.719>
                var geometry = Ellipse_177p719();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 9.71899986F, 2.7190001F), ColorBrush_AlmostDodgerBlue_FF118EFC());;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Shape Layer 2
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_16()
            {
                // Offset:<9.719, 2.719>
                var geometry = Ellipse_177p719();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 9.71899986F, 2.7190001F), ColorBrush_AlmostDodgerBlue_FF0C81E8());;
                return result;
            }

            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_17()
            {
                // Offset:<396.5, 357>
                if (_spriteShape_17 != null) { return _spriteShape_17; }
                var result = _spriteShape_17 = CreateSpriteShape(PathGeometry_5(), new Matrix3x2(1F, 0F, 0F, 1F, 396.5F, 357F));;
                result.Scale = new Vector2(0F, 0F);
                result.StrokeBrush = ColorBrush_White();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Transforms for BG Scale(1,1,0), Offset(-216,-106,0)
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(3459F, 3837F);
                // Offset:<-216, -106>, Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, -216F, -106F, 0F, 1F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                // PreComp layer: BG
                children.InsertAtTop(ContainerVisual_0());
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.156000003F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.101000004F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_2;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_3()
            {
                return (_cubicBezierEasingFunction_3 == null)
                    ? _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_3;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_4()
            {
                return (_cubicBezierEasingFunction_4 == null)
                    ? _cubicBezierEasingFunction_4 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0F, 1F))
                    : _cubicBezierEasingFunction_4;
            }

            ExpressionAnimation RootProgress()
            {
                if (_rootProgress != null) { return _rootProgress; }
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // PreComp layer: BG
            InsetClip InsetClip_0()
            {
                var result = _c.CreateInsetClip();
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: Bolas1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m11_to_6()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, -11F, StepThenHoldEasingFunction());
                // Frame 11.
                result.InsertKeyFrame(0.200000003F, -11F, HoldThenStepEasingFunction());
                // Frame 23.
                result.InsertKeyFrame(0.418181807F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.833000004F, 0.921000004F)));
                // Frame 50.
                result.InsertKeyFrame(0.909090936F, 6F, _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.326999992F), new Vector2(0.150000006F, 1F)));
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m28_to_18()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, -28F, StepThenHoldEasingFunction());
                // Frame 15.
                result.InsertKeyFrame(0.272727281F, -28F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.909090936F, 18F, CubicBezierEasingFunction_3());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz2
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m30_to_16()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, -30F, StepThenHoldEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.290909082F, -30F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.909090936F, 16F, CubicBezierEasingFunction_3());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m33_to_13()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, -33F, StepThenHoldEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.327272713F, -33F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.909090936F, 13F, CubicBezierEasingFunction_3());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_0()
            {
                // Frame 0.
                if (_scalarAnimation_0_to_1_0 != null) { return _scalarAnimation_0_to_1_0; }
                var result = _scalarAnimation_0_to_1_0 = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 11.
                result.InsertKeyFrame(0.200000003F, 0F, HoldThenStepEasingFunction());
                // Frame 23.
                result.InsertKeyFrame(0.418181807F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_1()
            {
                // Frame 0.
                if (_scalarAnimation_0_to_1_1 != null) { return _scalarAnimation_0_to_1_1; }
                var result = _scalarAnimation_0_to_1_1 = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 13.
                result.InsertKeyFrame(0.236363634F, 0F, HoldThenStepEasingFunction());
                // Frame 25.
                result.InsertKeyFrame(0.454545468F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0p3_to_0p916()
            {
                // Frame 0.
                if (_scalarAnimation_0p3_to_0p916 != null) { return _scalarAnimation_0p3_to_0p916; }
                var result = _scalarAnimation_0p3_to_0p916 = CreateScalarKeyFrameAnimation(0F, 0.300000012F, StepThenHoldEasingFunction());
                // Frame 13.
                result.InsertKeyFrame(0.236363634F, 0.300000012F, HoldThenStepEasingFunction());
                // Frame 21.
                result.InsertKeyFrame(0.381818175F, 0.915769994F, CubicBezierEasingFunction_4());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0p3_to_1p011()
            {
                // Frame 0.
                if (_scalarAnimation_0p3_to_1p011 != null) { return _scalarAnimation_0p3_to_1p011; }
                var result = _scalarAnimation_0p3_to_1p011 = CreateScalarKeyFrameAnimation(0F, 0.300000012F, StepThenHoldEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.145454541F, 0.300000012F, HoldThenStepEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.290909082F, 1.01143003F, CubicBezierEasingFunction_4());
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // -  Offset:<1729.5, 1918.5>
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.145454541F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: stroke2
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 4.
                result.InsertKeyFrame(0.0727272704F, 0F, HoldThenStepEasingFunction());
                // Frame 12.
                result.InsertKeyFrame(0.218181819F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: stroke4
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_2()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 6.5.
                result.InsertKeyFrame(0.118181817F, 0F, HoldThenStepEasingFunction());
                // Frame 14.5.
                result.InsertKeyFrame(0.263636351F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - PreComp layer: BG
            // - - Layer aggregator
            // - Layer: stroke3
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_3()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 9.
                result.InsertKeyFrame(0.163636357F, 0F, HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.309090912F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // - Layer: Shape Layer 3
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_4()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.327272713F, 0F, HoldThenStepEasingFunction());
                // Frame 32.
                result.InsertKeyFrame(0.581818163F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // PreComp layer: BG
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(3459F, 3837F);
                var shapes = result.Shapes;
                // Offset:<1729.5, 1918.5>
                shapes.Add(SpriteShape_00());
                // Layer: stroke2
                shapes.Add(SpriteShape_01());
                // Layer: stroke4
                shapes.Add(SpriteShape_02());
                // Layer: stroke3
                shapes.Add(SpriteShape_03());
                // Layer: Bolas1
                shapes.Add(ContainerShape_00());
                // Layer: Bolas2
                shapes.Add(ContainerShape_02());
                // Layer: cruz1
                shapes.Add(ContainerShape_04());
                // Layer: cruz2
                shapes.Add(ContainerShape_05());
                // Layer: cruz3
                shapes.Add(ContainerShape_06());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(796F, 714F);
                var shapes = result.Shapes;
                // Layer: Shape Layer 1
                shapes.Add(ContainerShape_07());
                // Layer: Shape Layer 2
                shapes.Add(ContainerShape_09());
                // Layer: Shape Layer 3
                shapes.Add(SpriteShape_17());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1496.5F, 2188.5F), StepThenHoldEasingFunction());
                // Frame 15.
                result.InsertKeyFrame(0.272727281F, new Vector2(1496.5F, 2188.5F), HoldThenStepEasingFunction());
                // Frame 25.
                result.InsertKeyFrame(0.454545468F, new Vector2(1734.5F, 1890.5F), _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.103F, 1F)));
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz2
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1488.5F, 2191.5F), StepThenHoldEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.290909082F, new Vector2(1488.5F, 2191.5F), HoldThenStepEasingFunction());
                // Frame 26.
                result.InsertKeyFrame(0.472727269F, new Vector2(1204.5F, 2298.5F), CubicBezierEasingFunction_4());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz3
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1496.5F, 2193.5F), StepThenHoldEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.327272713F, new Vector2(1496.5F, 2193.5F), HoldThenStepEasingFunction());
                // Frame 28.
                result.InsertKeyFrame(0.5090909F, new Vector2(1723.5F, 2406.5F), CubicBezierEasingFunction_4());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: stroke2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 4.
                result.InsertKeyFrame(0.0727272704F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: stroke4
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 6.5.
                result.InsertKeyFrame(0.118181817F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: stroke3
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 9.
                result.InsertKeyFrame(0.163636357F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: Bolas1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 11.
                result.InsertKeyFrame(0.200000003F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_4()
            {
                // Frame 0.
                if (_shapeVisibilityAnimation_4 != null) { return _shapeVisibilityAnimation_4; }
                var result = _shapeVisibilityAnimation_4 = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 13.
                result.InsertKeyFrame(0.236363634F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_5()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 15.
                result.InsertKeyFrame(0.272727281F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: BG
            // - Layer aggregator
            // Layer: cruz2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_6()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.290909082F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_7()
            {
                // Frame 0.
                if (_shapeVisibilityAnimation_7 != null) { return _shapeVisibilityAnimation_7; }
                var result = _shapeVisibilityAnimation_7 = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.327272713F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - Layer aggregator
            // Layer: Shape Layer 1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_8()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.145454541F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            internal Success_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(796F, 714F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                StartProgressBoundAnimation(_animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0, "Color", ColorAnimation_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0(), RootProgress());
                StartProgressBoundAnimation(_animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1, "Color", ColorAnimation_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1(), RootProgress());
                StartProgressBoundAnimation(_animatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8, "Color", ColorAnimation_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8(), RootProgress());
                StartProgressBoundAnimation(_containerShape_00, "Scale", ShapeVisibilityAnimation_3(), RootProgress());
                StartProgressBoundAnimation(_containerShape_01, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m11_to_6(), RootProgress());
                StartProgressBoundAnimation(_containerShape_01, "Scale.X", ScalarAnimation_0_to_1_0(), RootProgress());
                StartProgressBoundAnimation(_containerShape_01, "Scale.Y", ScalarAnimation_0_to_1_0(), RootProgress());
                StartProgressBoundAnimation(_containerShape_02, "Scale", ShapeVisibilityAnimation_4(), RootProgress());
                StartProgressBoundAnimation(_containerShape_03, "Scale.X", ScalarAnimation_0_to_1_1(), RootProgress());
                StartProgressBoundAnimation(_containerShape_03, "Scale.Y", ScalarAnimation_0_to_1_1(), RootProgress());
                StartProgressBoundAnimation(_containerShape_04, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m28_to_18(), RootProgress());
                StartProgressBoundAnimation(_containerShape_04, "Offset", OffsetVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_containerShape_04, "Scale", ShapeVisibilityAnimation_5(), RootProgress());
                StartProgressBoundAnimation(_containerShape_05, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m30_to_16(), RootProgress());
                StartProgressBoundAnimation(_containerShape_05, "Offset", OffsetVector2Animation_1(), RootProgress());
                StartProgressBoundAnimation(_containerShape_05, "Scale", ShapeVisibilityAnimation_6(), RootProgress());
                StartProgressBoundAnimation(_containerShape_06, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m33_to_13(), RootProgress());
                StartProgressBoundAnimation(_containerShape_06, "Offset", OffsetVector2Animation_2(), RootProgress());
                StartProgressBoundAnimation(_containerShape_06, "Scale", ShapeVisibilityAnimation_7(), RootProgress());
                StartProgressBoundAnimation(_containerShape_07, "Scale", ShapeVisibilityAnimation_8(), RootProgress());
                StartProgressBoundAnimation(_containerShape_08, "Scale.X", ScalarAnimation_0p3_to_1p011(), RootProgress());
                StartProgressBoundAnimation(_containerShape_08, "Scale.Y", ScalarAnimation_0p3_to_1p011(), RootProgress());
                StartProgressBoundAnimation(_containerShape_09, "Scale", ShapeVisibilityAnimation_4(), RootProgress());
                StartProgressBoundAnimation(_containerShape_10, "Scale.X", ScalarAnimation_0p3_to_0p916(), RootProgress());
                StartProgressBoundAnimation(_containerShape_10, "Scale.Y", ScalarAnimation_0p3_to_0p916(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_0, "TrimEnd", TrimEndScalarAnimation_0_to_1_0(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_1, "TrimEnd", TrimEndScalarAnimation_0_to_1_1(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_2, "TrimEnd", TrimEndScalarAnimation_0_to_1_2(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_3, "TrimEnd", TrimEndScalarAnimation_0_to_1_3(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_5, "TrimEnd", TrimEndScalarAnimation_0_to_1_4(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_01, "Scale", ShapeVisibilityAnimation_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_02, "Scale", ShapeVisibilityAnimation_1(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_03, "Scale", ShapeVisibilityAnimation_2(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_17, "Scale", ShapeVisibilityAnimation_7(), RootProgress());
            }

            public void DestroyAnimations()
            {
                _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_0.StopAnimation("Color");
                _animatedColorBrush_SemiTransparentAlmostDarkCyan_020065BD_to_AlmostDarkCyan_FF0065BD_1.StopAnimation("Color");
                _animatedColorBrush_SemiTransparentAlmostDodgerBlue_020C81E8_to_AlmostDodgerBlue_FF0C81E8.StopAnimation("Color");
                _containerShape_00.StopAnimation("Scale");
                _containerShape_01.StopAnimation("RotationAngleInDegrees");
                _containerShape_01.StopAnimation("Scale.X");
                _containerShape_01.StopAnimation("Scale.Y");
                _containerShape_02.StopAnimation("Scale");
                _containerShape_03.StopAnimation("Scale.X");
                _containerShape_03.StopAnimation("Scale.Y");
                _containerShape_04.StopAnimation("RotationAngleInDegrees");
                _containerShape_04.StopAnimation("Offset");
                _containerShape_04.StopAnimation("Scale");
                _containerShape_05.StopAnimation("RotationAngleInDegrees");
                _containerShape_05.StopAnimation("Offset");
                _containerShape_05.StopAnimation("Scale");
                _containerShape_06.StopAnimation("RotationAngleInDegrees");
                _containerShape_06.StopAnimation("Offset");
                _containerShape_06.StopAnimation("Scale");
                _containerShape_07.StopAnimation("Scale");
                _containerShape_08.StopAnimation("Scale.X");
                _containerShape_08.StopAnimation("Scale.Y");
                _containerShape_09.StopAnimation("Scale");
                _containerShape_10.StopAnimation("Scale.X");
                _containerShape_10.StopAnimation("Scale.Y");
                _pathGeometry_0.StopAnimation("TrimEnd");
                _pathGeometry_1.StopAnimation("TrimEnd");
                _pathGeometry_2.StopAnimation("TrimEnd");
                _pathGeometry_3.StopAnimation("TrimEnd");
                _pathGeometry_5.StopAnimation("TrimEnd");
                _spriteShape_01.StopAnimation("Scale");
                _spriteShape_02.StopAnimation("Scale");
                _spriteShape_03.StopAnimation("Scale");
                _spriteShape_17.StopAnimation("Scale");
            }

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
